---
output:
  pdf_document:
    fig_caption: yes
    number_sections: yes
    citation_package: natbib
urlcolor: black
linkcolor: black
fontsize: 12px
geometry: "left=3.5cm,right=2.5cm,top=2.5cm,bottom=2.5cm"
header-includes:
- \usepackage{placeins}
- \usepackage{setspace}
- \usepackage{chngcntr}
- \onehalfspacing
- \counterwithin{figure}{section}
- \counterwithin{table}{section}
- \usepackage[czech]{babel}
bibliography: uni.bib
csl: biomed-central.csl
---

<!-- Titulní strana  -->
\begin{titlepage}
\begin{center}
\textbf{GYMNÁZIUM, STŘEDNÍ PEDAGOGICKÁ ŠKOLA, OBCHODNÍ AKADEMIE A JAZYKOVÁ ŠKOLA s právem státní jazykové zkoušky ZNOJMO, příspěvková organizace} 

\vspace{2mm}

\line(1,0){425}

\vspace{2mm}

\tiny{669 02  Znojmo, Pontassievská 3 • tel.: 515158101 • fax: 515225230 • e-mail: info@gpoa.cz • www.gpoa.cz, IČ:49438816}
\end{center}

\vspace{1.5cm}

\begin{center}
\textbf{\large{Maturitní práce}}
\end{center}

\vspace{1.5cm}

Žák: David Beneš\\
Třída: E4.C \\
Školní rok: 2017/2018\\
Obor vzdělání: Informační technologie

\vspace{1.5cm}

Název maturitní práce: Tvorba počítačové hry

\vspace{1.5cm}

Vedoucí maturitní práce: Mgr. Milička Tomáš\\
Oponent maturitní práce:

\vspace{1.5cm}

Sociální partner: GYMNÁZIUM, STŘEDNÍ PEDAGOGICKÁ ŠKOLA, OBCHODNÍ 

\hspace{2.5cm}AKADEMIE A JAZYKOVÁ ŠKOLA s právem státní jazykové

\hspace{2.5cm}zkoušky ZNOJMO, příspěvková organizace\\
[1.5cm]
Práce odevzdána dne: (datum)\\
[1.5cm]
Podpis žáka: (podpis)
\end{titlepage}


<!-- PROHLÁŠENÍ -->
\section*{Prohlášení}

\vspace{1.5cm}

<<<<<<< HEAD
Prohlašuji,  že  jsem  maturitní  práci  vypracoval  samostatně  pod  vedením  Mgr. Tomáše Miličky  a  uvedl  v seznamu  literatury  a  zdrojů veškerou  použitou  literaturu  a  další informační zdroje.

\vspace{1.5cm}

Místo datum

\vspace{2cm}

David Beneš
=======
    Prohlašuji,  že  jsem  maturitní  práci  vypracoval  samostatně  pod  vedením  Mgr. Tomáše Miličky  a  uvedl  v seznamu  literatury  a  zdrojů veškerou  použitou  literaturu  a  další informační zdroje.
    
	\vspace{1.5cm}
	
    Místo datum
	
    \vspace{2cm}
	
    David Beneš
>>>>>>> c1c08118b0726763cb85146cc7045b93752ba4bd
    
\newpage
<!-- ANOTACE  -->
\section*{Anotace}

Maturitní práce se zaměřuje na programování v jazyce C\# v herním enginu Unity. V práci je popsán vývoj hry a veškeré problémy, které s vývojem souvisí.

**Klíčová slova**

hra, csharp, unity, programování

\pagebreak

<!-- OBSAH  -->
\tableofcontents

\pagebreak


# Úvod  
 Téma jsem si vybral, protože mě vždy zajímalo jak se hry vyvíjí. Dále jsem chtěl vědět, jestli vůbec takovou hru dokážu naprogramovat. Také jsem zastáncem názoru, že programování se dá naučit jedině praxí.

## Vymezení cílů
Mým hlavním cílem je naprogramovat hru pomocí jazyka C\#. Neměla by být moc obtížná na naučení, ale měla by být těžká na pokoření (@website:ez2play-hard2master). Game design by měl být jednoduchý a přehledný, ať se hráč jednoduše vyzná kde se právě nachází. Hra by se měla zaměřovat na schovávání se před nepřáteli, a ne na jejich zabíjení.


\pagebreak

# Využité programy

## Unity

### Představení
Unity je herní engine.
Je používaný pro vývoj jak indie (nezávislých), tak AAA her. Je v něm možná naprogramovat hru v jazyce C\#, který je rozšířen o mnoho Unity knihoven, ale i v JavaScriptu.

### Důvod pouzití
Unity jsem si vybral, protože se mi hned na první pohled zalíbilo. Má krásný a jednoduchý design. Také znám spoustu her, které jsou za pomocí Unity enginu vytvořené.
Velikým důvodem pro výběr byla také dostupnost v jazyce C\#, což ne všechny herní enginy nabízejí.

### Výhody
- Jednoduchost
- Je zdarma pro osobní i komerční účely (do \$100k)
- Dostupnost jazyka C\#

### Nevýhody
- Pro úplné nástroje je třeba zaplatit

### Alternativy
- Unreal Engine
	- Od společnosti Epic Games
	- Více se zaměřuje na systém akce a reakce, než se zaměřuje na programování
- CryEngine
	- Od společnosti Crytech

## Visual Studio

### Představení
Pro upravování C\# skriptů jsem použil program Visual Studio Community 2017 @website:vs. Tento program vytvořil microsoft, proto má skvělou podporu jazyka C\#.

### Důvod pouzití
Ve Visual Studiu jsme pracovali i v hodinách programování ve škole, takže jsem měl k programu velice blízko. Dalším důvodem bylo to, že Unity velice dobře pracuje s tímto programem. Nabízí snippets (CSNIPPETS), proto je mnohem jednodušší a rychlejší kód psát. Je tedy mnohem jednodušší soustředit se na to, co je důležité a né na pamatování si všech metod a tříd, které unity poskytuje.

### Výhody
- Je zdarma pro osobní i komerční účely pro jedince
- Dostupnost jazyka C\#
- Jednoduché debugování

### Nevýhody
- Není multiplatformní (neexistuje verze pro linux)

### Alternativy
- monodevelop
- atom
- vs code

\pagebreak

# Průběh vývoje
## Výběr žánru
Na začátku jsem musel vymyslet v jakém duchu budu hru vyvýjet. Jelikož mám velice rád stealth hry @STEALTH, rozhodl jsem se vytvořit v tomto duchu. Nechtěl jsem, aby hráč začil nějakou výzvu, a tak ve hře nejsou žádné zbraně. Pro záživnějsí průbeh jsem se rozhodl zahrnout do hry nějaké superschopnosti.

## Ovládání postavy
Hráč ovládá postavu pomocí základních WASD tlačítek. Pomocí myši míří a rozhlíží se po úrovni. Pro pohyb jsem využil Vector3 @VECTOR3 a to tak, že jsem k pozici postavy přičetl jednotkový vektor a vynásobil rychlostí, kterou jsem si vybral. Pro otáčení hráče ke kurzoru jsem prvně musel zjistit, kde je kurzor. To jsem udělal pomocí kamery, která je na scéně. Ta dokáže vypočítat, kam na jaký bod kurzor míří. Aby se postava nedívala do země, přičetl jsem výšku postavy k tomuto bodu. Pro samotné otočení postavy k bodu jsem musel využít quaternion @QUATERNION. Ten sice zjistí, jak daleko se musí postava otočit, ale poté je nutno ho převést na tzv. eulerAngles @EULERANGLES. Díky tomu pak víme, o kolik se na jednotlivých osách postava musí natočit.

## Schopnosti
Při výběru schopností jsem se nechal inspirovat ze stealth her a moba her. Hlavně pak Dishonored a Dota2.

### Blink
Blink je teleportace na krátkou vzdálenost. Pomáhá hráči k rychlému přesunu. 
Prvně jsem se rozhodl vytvořit vizuální zobrazení pro hráče. Vytvořil jsem čáru, které začala v postavě a končila na kurzoru hráče (pro získání kurzoru jsem využil stejný postup jako při otáčení postavy). Na konci čáry jsem přidal kostku, aby hráč věděl, kam se přesune. Poté jsem řešil maximální vzdálenost teleportu. Vytvořil jsem si proměnou, která uchovávála desetinné číslo, které určuje maximální vzálenost. Pomocí IF podmínky jsem zjistil, jestli vzdálenost postavy od konce čáry je delší než je tato proměná. Pokud ano zkrátím čáru na maximální vzdálenost ve směru kurzoru. Poté jsem musel zabránit teleportaci skrz zdi. Prvně jsem zjistil, jestli je na konci čáry zeď pomocí Physics.Raycast @RAYCAST. Pokud ano, tak čáru zkrátil na vzdálenost hráče od této zdi. Nakonec jsem musel vyřešit samotný teleport. To bylo velice jednoduché, protože stačilo nastavit pozici postavy na pozici, která je na konci čáry.

### Neviditelnost
Pro neviditelnost jsem použil globální proměnnou, kterou jsem si vytvořil. Tu jsem pak předával nepříteli, aby "nevnímal" hráče. Težší bylo zajistit, aby neviditelnost trvala nějakou dobu a pak se hráč opět zviditelni. 
Vytvořil jsem while cyklus a proměnou, která uchovávala čas, který může být hráč neviditelný. Každým průchodem cyklu jsem od této proměné odečetl sekundu pomocí Time.Deltatime @DELTATIME. Dokud byla proměná větší jak 0, tak byl hráč neviditelný. Aby hráč věděl, kdy je neviditelný musel jsem změnit barvu postavy. Prvně jsem získal materiál postavy a pak nastavil průhlednost nastavil na 1/3. Až se hráč opět zviditelnil, nastavil jsem zpět hodnotu 1.

### Cooldown
Aby hráč nemohl být neviditelný donekonečna, a nemohl se stále teleportovat musel jsem vytvořit cooldown. Pro cooldown jsem využil podobný cyklus jako pro neviditelnost. Jediné co jsem musel přidat byla proměná, která uchovává, jestli hráč muže schopnost použít. Před cyklem jsem ji nastavil na false a po cyklu opět na true. Aby šlo vidět, kolik času zbývá, rozhodl jsem se ho zakomponovat do UI.

## Nepřítel
## Cíl úrovní
Hlavní hráčův úkol je posbírat všechny klíče, které jsou po úrovni rozmístění. Při tom se musí schovávat před zrakem nepřátel. Sebrání všech klíčů však není konec, hráč se stále musí dostat do cíle, který právě otevřel. Jakmile hráče nepřítel spatří, zastřelí ho a tím se úroveň restartuje.  

\pagebreak

# Problémy vývoje

## Úvod
Jelikož jsem začátečník v programování a zároveň v enginu Unity, narazil jsem na spoustu problémů. Pár větších bych teď chtěl popsat.

## Pohyb a rotace postavy
Při pohybu jsem musel upravovat rychlost. Po té jsem narazil na problém při kolizích postavy a země či zdí. Postava stále propadávala. Zjistil jsem, že to bylo ve velikosti collideru země, o něco málo jsem o zvětšil a vše bylo v pořádku.
Při rotaci to ovšem bylo horší. Chtěl jsem, aby se postava otáčela ke kurzoru. Byl zde probém zjištění místa kurzoru. Ten jsem docela rychle vyřešil pomocí některých metod, které unity poskytuje. Po té se ale postava stále koukala do země, takže jsem se nemohl normálně pohybovat. Pomocí youtube videí jsem zjistil, že se dá nalézt kurzor elegantněji. To mi sice pomohlo, ale stále se postava dívala trošku jinam, než měla. Nakonec jsem to vyřešil přičtením této odchylky a vše funguje normálně.

## Otáčení nepřátel


#Závěr
S hrou jsem nadmíru spokojen. Získal jsem mnoho programovacích zkušeností, které by se mi jinak nenaskytli. Dokázal jsem využít již naučené techniky a k nim přidat i nové věci.


## Zhodnocení cílů
Mnoho svých cílů jsem splnil přesně dle očekávání. Některé jsem musel upravit, aby pro hráče dávali větší smysl a hra byla hratelná. Zkušební verzi jsem poskytoval kamarádům, kteří mi poté poskytli odezvu. Díky tomu jsem například přidal FOG OF WAR (CITACE FOG OF WAR), aby hra nebyla tak jednoduchá.

## Feedback???
Hru možná budu sdílet na redditu

\pagebreak
<!-- CITACE  -->
<!--\section*{Citace} -->
